### ISSUE TITLE
Diagrama de entidade relacionamento

### ISSUE THREAD

**Issue by Anderson-kw** [MuriloFekete/Recruitment-System#11]

**Comment by GustavoPuente** [comment]
add

**Comment by Anderson-kw** [comment]
https://docs.google.com/document/d/1YOduNsh5a7LMXrxSCq9zRL8esB7B6k1Hla2zjLfUoJk/edit?usp=sharing

**Comment by Anderson-kw** [comment]
https://www.canva.com/design/DAGXaUmlG48/MNiPb8I_Vk5QziLF6arVFQ/edit

**Comment by Anderson-kw** [comment]
[Diagrama Entidade Relacionamento](https://lucid.app/lucidchart/75ae460a-f08b-435e-8e59-025a86a42b58/edit?viewport_loc=-3094%2C-2812%2C8281%2C2931%2C0_0&invitationId=inv_a6594ee9-8b5a-41ed-9edd-5306bd0939fb)
